version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task-grandy
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
  grandy-api:
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: grandy-api
    depends_on:
      - postgres
    ports:
      - "4004:4004"
    restart: always

volumes:
  postgres-data:
  pgadmin-data:
  