version: "2"

services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - 4004:4004
      - 9229:9229 # debugger port
    volumes:
      - ./apps/backend:/app/apps/backend
      - /app/apps/backend/node_modules
    command: yarn start:docker
