services:
  - type: web
    env: node
    name: markers-prod-back1
    repo: https://github.com/vitalii-minchuk/markers
    buildFilter:
      paths:
        - apps/backend/**
    buildCommand: yarn && yarn build --filter=backend
    startCommand: cd apps/backend; yarn start

  - type: web
    env: static
    name: markers-prod-front1
    repo: https://github.com/vitalii-minchuk/markers
    buildFilter:
      paths:
        - apps/frontend/**
    buildCommand: yarn && yarn build --filter=frontend
    staticPublishPath: ./apps/frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
